name: branch-labeler

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited # for base branch change

jobs:
  call:
    uses: the9ball/branch-labeler/.github/workflows/branch-labeler.yaml
    permissions:
      contents: write # for creating label
      pull-requests: write
    with:
      # Branch名を表す正規表現です。
      # Bashの構文に準拠します。
      branch_name_filter: "[feature|release]/.*"
