name: create-merged-branch
on:
  pull_request:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .
          sparse-checkout-cone-mode: false
      - name: setup
        run: git remote set-url origin https://github-actions:${{ github.token }}@github.com/${{ github.repository }}
      - name: push
        run: |
          git branch -f temp-${{ github.run_id }}
          git push origin temp-${{ github.run_id }}:${{ github.head_ref }}-merged
