name: delete-merged-branch
on:
  pull_request:
    types:
      - closed

concurrency:
  group: merged-branch
  cancel-in-progress: true

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: .
          sparse-checkout-cone-mode: false
      - name: setup
        run: git remote set-url origin https://github-actions:${{ github.token }}@github.com/${{ github.repository }}
      - name: delete
        run: |
          git push --delete origin ${{ github.head_ref }}-merged || :
