name: test
on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
      - run: exit 0
        if: failure()