name: test
on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo MESSAGE_HEAD=$("${{ github.event.head_commit.message }}" | head -n1) >> $env:GITHUB_ENV
      - run: echo "${{ env.MESSAGE_HEAD }}"
      - run: exit 0
        if: failure()