name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: return 1

  test2:
    needs: ["test"]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: failure()
    steps:
      - run: echo "test2"
