name: test
on:
  push:
    branches:
      - "test/*"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: |
          echo "::set-env name=BRANCH::$( echo ${{ github.ref }} | sed -e 's|refs/heads/||' )"
      # - uses: octokit/request-action@v2.x
      #   id: get_latest_release
      #   with:
      #     route: POST /repos/:owner/:repo/pulls
      #     owner: ${{ github.repository_owner }}
      #     repo: ${{ github.repository }}
      #     headers: |
      #       {
      #         title: "test"
      #         head: "${BRANCH}"
      #         base: "master"
      #         body: "bodytext"
      #         maintainer_can_modify: true
      #       }
      #     ACTIONS_STEP_DEBUG: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      - run: |
          curl -i \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -X POST -d '{ \
              "title": "test" \
              "head": "${BRANCH}" \
              "base": "master" \
              "body": "bodytext" \
              "maintainer_can_modify": true \
            }' \
            https://api.github.com/repos/${{github.repository_owner}}/${{github.repository}}/pulls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

