name: test
on:
  pull_request:
    types: [labeled, unlabeled, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      OUTPUTDIR: ${{ github.workspace }}/temp
    steps:
      - run: echo ${OUTPUTDIR}
