name: test
on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: |
          echo "MESSAGE=$(echo "${{ github.event.head_commit.message }}" | head -n1)" >> $GITHUB_ENV
          echo "PR_URL=https://github.com/${{ github.repository }}/pull/$(echo ${MESSAGE} | sed -E 's/^.*#([0-9]+).*$/\1/')" >> $GITHUB_ENV
      - run: |
          echo "${MESSAGE}"
          echo "${PR_URL}"
      - run: exit 0
        if: failure()