name: test
on:
  push:
    branches: [ test* ]
  pull_request:
    branches: [ test* ]
  workflow_dispatch:
    inputs:
      test-value:
        description: 'test value'
        required: false
        type: string
        default: null

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo "${{ inputs.test-value || github.head_ref || github.ref_name }}"
