name: test
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**/.gitignore"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: cat "${GITHUB_EVENT_PATH}"
      - run: exit 0
        if: failure()