name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  TARGET_BRANCH: master

jobs:
  skip_ci:
    if: github.event_name != 'workflow_dispatch' || github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: nop
        if: false
        run: exit 0

  test:
    needs: skip_ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: export
