name: test
on:
  push:
    branches:
      - "master"

jobs:
  test:
    if: ${{false}}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: exit 0
        if: failure()
